### ISSUE TITLE
Minor corrections

### ISSUE THREAD

**Issue by abrudz** [fastai/apl-study#18]
I suggest using a spell-checker to catch things like:
- [ ] gl<ins>y</ins>p<del>y</del>h
- [ ] ignor<del>r</del>ed
- [ ] Reciproc<del>o</del><ins>a</ins>l (×2)
- [ ] argu<del>e</del>ment (×6)
- [ ] argumen<del>e</del>t
- [ ] mon<del>d</del>adic
- [ ] occurr<del>a</del><ins>e</ins>nce 
- [ ] Mon<del>d</del>a<ins>d</ins>ic
- [ ] max<del>u</del><ins>i</ins>mum

### Basics

The note about element-wise application is inconsistent. Either mention it for each and every scalar function, or make a general note at the top of the "Basic math functions" that the rule applies to all but dyadic `?`

- [ ] use parenthes<del>i</del><ins>e</ins>s. The parenthes<del>i</del><ins>e</ins>s are
- [ ] negative numbers <del>because</del><ins>become</ins> positive
- [ ] Complex numbers are divided <del>it’s</del>
- [ ] <ins>by their</ins> magnitude
- [ ] <del>`e`</del><ins>the mathematical constant *e*</ins> (×2)
- [ ] Gives a random <del>number</del>integer between 1 and the input argument<ins> or, in the case of 0, a random non-integer between 0 and 1.</ins>
- [ ] <del>`pi`</del><ins>*π* (pi)</ins>
- [ ] The <del>LHS defines what</del><ins>left argument selects</ins> function<ins>(s) to apply</ins><del> is returned</del>
- [ ] the mathematical constant <del>e</del><ins>*e*</ins>
- [ ] log<del>2</del><ins>₂</ins>(32)
- [ ] <del>parenthesis first, then </del>right to left<ins>, evaluating parentheses when encountered</ins>
- [ ] applied<ins>,</ins> vectors
- [ ] `1 2 3×2`<del>,</del> creates
- [ ] strength th<del>e</del><ins>a</ins>n function
- [ ] examples<ins>,</ins> remember
- [ ] There’<del>s</del><ins>re</ins> 2 interesting things
- [ ] The `b←3 4` example seems to serve no purpose.
- [ ] <del>generate and use side-effects</del><ins>perform a computation in multiple steps</ins>
- [ ] a condition for <del>the input value</del><ins>a result</ins>
- [ ] <ins>R</ins><del>For r</del>ecursion <del>it </del>can be simplified using
- [ ] <del>`a b ← 3 4`</del><ins>`(a b) ← 3 4`</ins> [omitting parentheses in multiple assignment is discouraged]
- [ ] Reshape will <del>broadcast</del><ins>recycle elements of</ins>
- [ ] is <del>null</del><ins>the empty vector</ins> [nulls are something else]
- [ ] `⍬`<ins>` ⍝ shorthand for (0⍴0)`</ins>
- [ ] special meaning<ins>s</ins> that are
- [ ] <del>(6.4.1( in the [Mastering Dyalog APL book](https://www.dyalog.com/uploads/documents/MasteringDyalogAPL.pdf)  for more information on what each means.</del> [the entire text there is given verbatim here]
- [ ] in the quote from the book, the symbols should be as code, `_` should be `-` or `─`, and ∮ should be `∊`.
- [ ] has a<del> null length</del></ins>n empty shape</ins>

### First functions

- [ ] is <del>a boolean</del> equal<ins> and returns a boolean result</ins>
- [ ] A <ins>simple </ins>scalar is <del>not </del>an array <del>and so it there is</del><ins>with</ins> no nesting.
- [ ] An <del>unnested </del>array <ins>of simple scalars </ins>has depth 1.
- [ ] An array that is an array of <ins>simple </ins>arrays has depth 2.
- [ ] In other words<ins>,</ins> it is equal
- [ ] For a vector, or rank 1 array, this is the same as it’s shape<ins> but as a scalar</ins>.
- [ ] 35 <del>can be divided by</del> cleanly
- [ ] Gives the <del>numbers</del><ins>elements</ins> from the left
- [ ] <del>`^`</del><ins>`∧`</ins>
- [ ] To generate an<del>d</del> array with various patterns<ins>,</ins> you
- [ ] Array of shape 0 is <del>null</del><ins>an empty vector</ins> and the index locations of a shape 0 array is <del>null</del><ins>an empty vector</ins>.
- [ ] the <del>`⍵`</del><ins>right argument</ins> value<ins>s are</ins> <del>is </del>in the <del>`⍺` object</del><ins>left argument</ins>
- [ ] gives <del>in </del>index
- [ ] to a <del>real</del><ins>natural</ins> number
- [ ] which interval <del>if</del><ins>a value</ins> falls in
- [ ] example, <del>`⍵`</del><ins>the left argument</ins> is [note mistake]
- [ ] 2<del>-</del><ins>–</ins>4 <ins>(excluding 4)</ins> [etc.]
- [ ] <del>`⍺`</del><ins>The right argument</del> is `1 2 3 4 5 6 7` [note mistake, including in the following]
- [ ] + [seems to be a MarkDown mistake ×4]
- [ ] near<del>ing</del><ins>est</ins>nearing whole whole

**Comment by Isaac-Flath** [comment]
These changes should be all addressed by these 2 PRs.

+ https://github.com/fastai/apl-study/pull/19
+ https://github.com/fastai/apl-study/pull/20
